with RAW_ORDERS as(
    select * from O_LIST_DB.RAW.RAW_ORDERS
)
select CUSTOMER_ID as CUSTOMER_ID
,ORDER_APPROVED_AT as ORDER_APPROVED_AT
,ORDER_DELIVERED_CARRIER_DATE as ORDER_DELIVERED_CARRIER_DATE
,ORDER_DELIVERED_CUSTOMER_DATE as ORDER_DELIVERED_CUSTOMER_DATE
,ORDER_ESTIMATED_DELIVERY_DATE as ORDER_ESTIMATED_DELIVERY_DATE
,ORDER_ID as ORDER_ID
,ORDER_PURCHASE_TIMESTAMP as ORDER_PURCHASE_TIMESTAMP
,ORDER_STATUS as ORDER_STATUS
from RAW_ORDERS