{{config(materialized='table')}}

with RAW_CUSTOMERS as(
    select * from O_LIST_DB.DEV.SRC_CUSTOMERS
)
select CUSTOMER_ID as CUSTOMER_ID
,CUSTOMER_CITY as CUSTOMER_CITY
,CUSTOMER_STATE as CUSTOMER_STATE
,CUSTOMER_UNIQUE_ID as CUSTOMER_UNIQUE_ID
,CUSTOMER_ZIP_CODE_PREFIX as CUSTOMER_ZIP_CODE_PREFIX
from RAW_CUSTOMERS