with RAW_GEOLOCATION as(
    select * from O_LIST_DB.RAW.RAW_GEOLOCATION
)
select GEOLOCATION_CITY as GEOLOCATION_CITY
,GEOLOCATION_LAT as GEOLOCATION_LAT
,GEOLOCATION_LNG as GEOLOCATION_LNG
,GEOLOCATION_STATE as GEOLOCATION_STATE
,GEOLOCATION_ZIP_CODE_PREFIX as GEOLOCATION_ZIP_CODE_PREFIX
from RAW_GEOLOCATION