with RAW_SELLERS as(
    select * from O_LIST_DB.RAW.RAW_SELLERS
)
select SELLER_ID as SELLER_ID
,SELLER_CITY as SELLER_CITY
,SELLER_STATE as SELLER_STATE
,SELLER_ZIP_CODE_PREFIX as SELLER_ZIP_CODE_PREFIX
from RAW_SELLERS