with RAW_CATEGORY as(
    select * from O_LIST_DB.RAW.RAW_CATEGORY
)
select PRODUCT_CATEGORY_NAME as PRODUCT_CATEGORY_NAME
,PRODUCT_CATEGORY_NAME_ENGLISH as PRODUCT_CATEGORY_NAME_ENGLISH
from RAW_CATEGORY