with RAW_ORDER_REVIEWS as(
    select * from O_LIST_DB.RAW.RAW_ORDER_REVIEWS
)
select ORDER_ID as ORDER_ID
,REVIEW_ID as REVIEW_ID
,REVIEW_SCORE as REVIEW_SCORE
,REVIEW_COMMENT_TITLE as REVIEW_COMMENT_TITLE
,REVIEW_COMMENT_MESSAGE as REVIEW_COMMENT_MESSAGE
,REVIEW_CREATION_DATE as REVIEW_CREATION_DATE
,REVIEW_ANSWER_TIMESTAMP as REVIEW_ANSWER_TIMESTAMP
from RAW_ORDER_REVIEWS