with raw_products as(
    select * from O_LIST_DB.RAW.RAW_PRODUCTS
)
select PRODUCT_ID as PRODUCT_ID
,PRODUCT_CATEGORY_NAME as PRODUCT_CATEGORY_NAME
,PRODUCT_DESCRIPTION_LENGHT as PRODUCT_DESCRIPTION_LENGHT
,PRODUCT_HEIGHT_CM as PRODUCT_HEIGHT_CM
,PRODUCT_LENGTH_CM as PRODUCT_LENGTH_CM
,PRODUCT_NAME_LENGHT as PRODUCT_NAME_LENGHT
,PRODUCT_PHOTOS_QTY as PRODUCT_PHOTOS_QTY
,PRODUCT_WEIGHT_G as PRODUCT_WEIGHT_G
,product_width_cm as product_width_cm
from raw_products