{{config(materialized='table')}}

with RAW_ORDER_ITEMS as(
    select * from O_LIST_DB.RAW.RAW_ORDER_ITEMS
)
select ORDER_ID as ORDER_ID
,ORDER_ITEM_ID as ORDER_ITEM_ID
,PRODUCT_ID as PRODUCT_ID
,SELLER_ID as SELLER_ID
,FREIGHT_VALUE as FREIGHT_VALUE
,PRICE as PRICE
,SHIPPING_LIMIT_DATE as SHIPPING_LIMIT_DATE
from RAW_ORDER_ITEMS