with RAW_ORDER_PAYMENTS as(
    select * from O_LIST_DB.RAW.RAW_ORDER_PAYMENTS
)
select ORDER_ID as ORDER_ID
,PAYMENT_INSTALLMENTS as PAYMENT_INSTALLMENTS
,PAYMENT_SEQUENTIAL as PAYMENT_SEQUENTIAL
,PAYMENT_TYPE as PAYMENT_TYPE
,PAYMENT_VALUE as PAYMENT_VALUE
from RAW_ORDER_PAYMENTS