-- referencing : staging layer : raw data


with SRC_ORDERS as(
    select * from {{ ref('src_orders') }}
)

select CUSTOMER_ID as CUSTOMER_ID
,ORDER_APPROVED_AT as ORDER_APPROVED_AT
,ORDER_DELIVERED_CUSTOMER_DATE as ORDER_DELIVERED_CUSTOMER_DATE
,ORDER_ESTIMATED_DELIVERY_DATE as ORDER_ESTIMATED_DELIVERY_DATE
,ORDER_ID as ORDER_ID
,ORDER_PURCHASE_TIMESTAMP as ORDER_PURCHASE_TIMESTAMP
,INITCAP(trim(ORDER_STATUS)) as ORDER_STATUS 
from SRC_ORDERS